# This file was generated by GoReleaser. DO NOT EDIT.
cask "opssh" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "32d5d8d509ef5d5ccb68b0101a96dc2f68bd23d7cdbce261e09f6e51aa8fc9f3"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
    on_arm do
      sha256 "c7bfb0d8ffa740fb3ae5ea6c6a2605de637e85df2568311ded8591ace375eacc"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e30c126401740ec713169ba46c2b73f6304dc9a537b76f0cd89a808846e0e2c"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_linux_amd64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
    on_arm do
      sha256 "c415fb6978c18c5d3da3cd4082c4866909ee720fa0018ebec5b7967b472a98d1"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_linux_arm64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
  end

  name "opssh"
  desc "Manage OpenSSH hosts backed by the 1Password SSH Agent"
  homepage "https://github.com/vlyl/opssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opssh"

  # No zap stanza required

end
