# This file was generated by GoReleaser. DO NOT EDIT.
cask "opssh" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "0c3122830640a93e3499c9f072415ca84ab2e1a83936f3d893c19ec7fdf0dbe2"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
    on_arm do
      sha256 "8c823dc14f9656cfe6bc2be1aee70a6eceaf829ef5ad3b2654eedf781e5bcdbb"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2c556cb461db619872c80e30990c349c03a251841f13041c1e4ceed5f306ea0"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_linux_amd64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
    on_arm do
      sha256 "af48980f082f5dd010cd96fffc41de28d97fc6e462bc926dbccef475c71e1849"
      url "https://github.com/vlyl/opssh/releases/download/v#{version}/opssh_#{version}_linux_arm64.tar.gz",
        verified: "github.com/vlyl/opssh/"
    end
  end

  name "opssh"
  desc "Manage OpenSSH hosts backed by the 1Password SSH Agent"
  homepage "https://github.com/vlyl/opssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opssh"

  # No zap stanza required

end
